### CPIH Historic Inflation Data
Downloads as an Excel from:
https://www.ons.gov.uk/file?uri=/economy/inflationandpriceindices/datasets/consumerpriceinflation/current/consumerpriceinflationdetailedreferencetables.xlsx

Relevant time series is Table 37.

Uses CPIH since RPI is no longer considered for inflation by ONS.

In [2]:
import pandas as pd

In [3]:
path = '../data/raw/consumerpriceinflationdetailedreferencetables.xlsx'

df = pd.read_excel(path, sheet_name = 'Table 37',skiprows=6)
df.head()

,index date,name,CPIH ALL ITEMS,FOOD AND NON-ALCOHOLIC BEVERAGES,FOOD,BREAD & CEREALS,MEAT,FISH,"MILK, CHEESE & EGGS",OILS & FATS,...,"Energy, Food, Alcohol & Tobacco",Energy & Non-processed Food,Energy & Seasonal Food,"Education, Health & Social Protection",CPIH excluding tobacco,Industrial Goods,Miscellaneous and Other Services,CPIH excluding owner occupiers' housing costs,CPIH excluding council tax,CPIH excluding owner occupiers' housing costs and council tax and rates
0,198801.0,1988-01-01 00:00:00,46.851,47.901,48.244,50.053,53.741,43.321,48.488,45.461,...,36.679,37.044,33.852,22.323,48.106,78.883,26.778,47.734,47.304,48.329
1,198802.0,1988-02-01 00:00:00,46.998,48.174,48.501,50.353,53.386,43.670,48.523,45.921,...,36.761,37.084,33.968,22.340,48.259,79.037,26.915,47.884,47.455,48.486
2,198803.0,1988-03-01 00:00:00,47.202,48.324,48.643,50.311,53.721,43.130,48.551,46.108,...,36.831,37.144,33.976,22.455,48.476,79.399,26.968,48.042,47.667,48.652
3,198804.0,1988-04-01 00:00:00,47.801,48.592,48.894,50.548,53.736,43.151,48.861,46.249,...,37.198,37.531,34.434,22.510,49.085,80.067,27.098,48.707,48.184,49.214
4,198805.0,1988-05-01 00:00:00,48.044,48.714,48.968,50.970,54.186,42.799,48.770,46.346,...,37.360,37.688,34.535,22.544,49.336,80.623,27.213,48.941,48.435,49.459

#### Cleaned output

In [5]:
df = df[['name','CPIH ALL ITEMS']]
df.head()

                  name  CPIH ALL ITEMS
0  1988-01-01 00:00:00          46.851
1  1988-02-01 00:00:00          46.998
2  1988-03-01 00:00:00          47.202
3  1988-04-01 00:00:00          47.801
4  1988-05-01 00:00:00          48.044

In [8]:
df.to_csv('../data/cpih_clean.csv')